// discovery — the well-known document. Shared by the worker and the MCP catalog (one source).
import { DONATE_URL, qpuLicenceHostOf, donateUrl } from './hologram.js'

export const qpuDiscoveryOf = (origin: string) => ({
  worker: 'uuidna-lean',
  host: qpuLicenceHostOf(),
  origin,
  donate: donateUrl(origin),
  wallet: DONATE_URL,
  mcp: `${origin}/mcp`,
  readings: ['seat', 'width', 'hologram', 'chip', 'merkaba', 'experience', 'live', 'metrics', 'speed', 'fractal', 'scale', 'og', 'nav', 'sidebar', 'search', 'superpositions', 'gateways', 'bindings', 'environment', 'standing', 'theorems', 'cited', 'axioms', 'wings', 'register', 'publications', 'library', 'books', 'cern', 'lhc', 'widgets', 'events', 'boot'] as const,
  endpoints: {
    '/': 'three readings, one machine, environment auto-recognized and fused',
    '/seat': 'LANES QPU — empty chip; environment still fused',
    '/width': 'BindingPoint pentagram — CPU GPU RAM CACHE STORAGE',
    '/hologram': 'octet planes; HTML is fourteen VE faces and one empty center',
    '/chip': 'novelty chip — two 7-ray rosettes fused at 0, CPU/GPU self-balance',
    '/merkaba': 'same reading as /chip',
    '/experience': 'inner and outer rotors — one involution',
    '/live': 'occupancy now — k walks fourteen VE faces',
    '/metrics': 'formula vs peer, every row must match',
    '/speed': 'constructor µs vs 2^n climbs for n that finish',
    '/fractal': 'fused pentagram · hologram · fourteen VE faces · all serverless',
    '/scale': 'peers + native transports + serverless lanes',
    '/og': 'hero Open Graph constructor — 1200×630',
    '/og.svg': 'hero Open Graph card — same pentagram as the homepage',
    '/sse': 'server-sent events of scale and live occupancy',
    '/ws': 'WebSocket — MCP JSON-RPC or {op}',
    '/peers': 'worker origins including QPU_PEERS',
    '/nav': 'nav computed upon request',
    '/sidebar': 'sidebar computed upon request (?path=)',
    '/search': 'deep site analysis of every licensed host; constructors only (?q=&site=&kind=)',
    '/superpositions': 'fourteen VE faces with referer, door, angles',
    '/gateways': 'fourteen VE-face neighbours are capacity gateways — every handle bit is a usable mask',
    '/bindings': 'src/bindings/* — every provider fused; drivers auto-recognize env',
    '/providers': 'cloudflare google aws azure ibm oracle hardware arch',
    '/environment': 'always fused: host + bound drivers + empty chip',
    '/standing': 'uuidna Lean keys this worker cites',
    '/theorems': 'Lean theorems — fourteen sealed uuidna keys; mint empty',
    '/cited': 'same reading as /theorems',
    '/axioms': 'Lean axioms — fourteen Lean wings; axiom empty',
    '/wings': 'same reading as /axioms',
    '/register': 'DOI-grade Lean register — proven handles sealed by decide; mint empty',
    '/publications': 'same reading as /register',
    '/library': 'public combinatorial books — 10¹⁴ seats, Lean leads, no verse, cost 0, when never',
    '/books': 'same reading as /library',
    '/cern': 'Lean CERN — fourteen named CERN HTTPS APIs; leads are the Lean register fused onto INSPIRE; mint empty',
    '/lhc': 'same reading as /cern',
    '/widgets': 'licensed-site chrome — UUID streams only; payload off; fourteen Glagolitic glyphs and one empty center',
    '/events': 'fourteen UI event kinds occupying VE faces',
    '/boot': 'boot matrix — eight Alpine ISAs times trinity parts',
    '/sitemap.xml': 'constructor sitemap',
    '/robots.txt': 'Allow / and Sitemap',
    '/mcp': 'JSON-RPC MCP (GET discovery, POST tools/call)',
    '/.well-known/qpu.json': 'this document',
    '/.well-known/mcp.json': 'MCP discovery',
  },
})
