// discovery — the well-known document. Shared by the worker and the MCP catalog (one source).
import { COINS, DONATE_URL, RAYS, VE_FACES, qpuLicenceHostOf, qpuSeatOf, donateUrl } from './hologram.js'

export const qpuDiscoveryOf = (origin: string) => ({
  worker: 'uuidna-lean',
  host: qpuLicenceHostOf(),
  origin,
  donate: donateUrl(origin),
  wallet: DONATE_URL,
  mcp: `${origin}/mcp`,
  seat: qpuSeatOf().seat,
  decide: 'lean' as const,
  invented: false as const,
  mint: 'empty' as const,
  mass: true as const,
  online: true as const,
  coordinated: true as const,
  alternate: true as const,
  enabled: true as const,
  default: true as const,
  crawl: false as const,
  rotors: COINS,
  rays: RAYS,
  faces: VE_FACES,
  readings: ['seat', 'width', 'hologram', 'chip', 'merkaba', 'experience', 'live', 'metrics', 'speed', 'fractal', 'scale', 'og', 'nav', 'sidebar', 'search', 'superpositions', 'gateways', 'bindings', 'environment', 'standing', 'theorems', 'cited', 'axioms', 'wings', 'register', 'publications', 'zenodo', 'library', 'books', 'essays', 'stripe', 'cern', 'lhc', 'fuse', 'internet', 'train', 'clusters', 'solve', 'reward', 'claim', 'compliance', 'green', 'widgets', 'events', 'boot', 'tesla'] as const,
  endpoints: {
    '/': 'three readings, one machine — mass online coordinated discovery enabled by default on inner/outer alternate; seat empty; only Lean decides',
    '/seat': 'LANES QPU — empty chip; environment still fused',
    '/width': 'BindingPoint pentagram — CPU GPU RAM CACHE STORAGE',
    '/hologram': 'octet planes; HTML is fourteen VE faces and one empty center',
    '/chip': 'novelty chip — two 7-ray rosettes fused at 0, CPU/GPU self-balance',
    '/merkaba': 'same reading as /chip',
    '/experience': 'inner and outer rotors — one involution',
    '/live': 'occupancy now — k walks fourteen VE faces',
    '/metrics': 'formula vs peer, every row must match',
    '/speed': 'constructor µs vs 2^n climbs for n that finish',
    '/fractal': 'fused pentagram · hologram · fourteen VE faces · all serverless',
    '/scale': 'peers + native transports + serverless lanes',
    '/og': 'hero Open Graph constructor — 1200×630',
    '/og.svg': 'hero Open Graph card — same pentagram as the homepage',
    '/sse': 'server-sent events of scale and live occupancy',
    '/ws': 'WebSocket — MCP JSON-RPC or {op}',
    '/peers': 'worker origins including QPU_PEERS',
    '/nav': 'nav computed upon request',
    '/sidebar': 'sidebar computed upon request (?path=)',
    '/search': 'deep site analysis of every licensed host; constructors only (?q=&site=&kind=)',
    '/superpositions': 'fourteen VE faces with referer, door, angles',
    '/gateways': 'fourteen VE-face neighbours are capacity gateways — every handle bit is a usable mask',
    '/bindings': 'src/bindings/* — every provider fused; drivers auto-recognize env',
    '/providers': 'cloudflare google aws azure ibm oracle hardware arch',
    '/environment': 'always fused: host + bound drivers + empty chip',
    '/standing': 'uuidna Lean keys this worker cites',
    '/theorems': 'Lean theorems — fourteen sealed uuidna keys; mint empty',
    '/cited': 'same reading as /theorems',
    '/axioms': 'Lean axioms — fourteen Lean wings; axiom empty',
    '/wings': 'same reading as /axioms',
    '/register': 'DOI-grade Lean register — proven handles sealed by decide; monitors Zenodo; mint empty',
    '/publications': 'same reading as /register',
    '/zenodo': 'watch Zenodo for Lean publications — parent DOI, named API, not a crawl',
    '/library': 'public combinatorial library of 10¹⁴-seat books — UUID clusters magnitudes bigger, Lean leads, no verse, cost 0, when never',
    '/books': 'same reading as /library',
    '/essays': 'same reading as /library — paginated UUID hex-glyph stripes',
    '/stripe': 'theorem Open Graph of one UUID stripe — 2×7 cross-references and rotations',
    '/cern': 'Lean CERN — fourteen named CERN HTTPS APIs; leads are the Lean register fused onto INSPIRE; mint empty',
    '/lhc': 'same reading as /cern',
    '/fuse': 'every named API that may fill quantum capacity by solving — 2×7 witness clusters',
    '/internet': 'unrestricted HTTPS to fused solving APIs by default — wildcards refuse',
    '/train': 'recognise any 2×7 witness clusters in any prose — never stored',
    '/clusters': 'same reading as /train',
    '/solve': 'automate problem solving by biggest risk–reward — prize, bounty, funding',
    '/reward': 'same reading as /solve',
    '/claim': 'claim the claimable, claim bold, stay lean — each claim checks prior art',
    '/compliance': 'same reading as /claim',
    '/green': 'release green — proofs, compliance, Zenodo monitor',
    '/widgets': 'licensed-site chrome — UUID streams only; payload off; fourteen Glagolitic glyphs and one empty center',
    '/events': 'fourteen UI event kinds occupying VE faces',
    '/boot': 'boot matrix — eight Alpine ISAs times trinity parts',
    '/tesla': 'Tesla.lean as one analog-hardware quantum cluster computed in hex — unexplored use cases on the massive online wave; patents stay cited as arithmetic; only Lean decides',
    '/sitemap.xml': 'constructor sitemap',
    '/robots.txt': 'Allow / and Sitemap',
    '/mcp': 'JSON-RPC MCP (GET discovery, POST tools/call)',
    '/.well-known/qpu.json': 'this document',
    '/.well-known/mcp.json': 'MCP discovery',
  },
})
